//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-11/28/2011 06:21 AM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 09:14:11 AM GMT-06:00 
//


package mx.com.longino.entity;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import org.codehaus.jackson.map.annotate.JsonDeserialize;

import mx.com.longino.util.DateHandlerDeserializable;

import com.bharatthippireddy.patient.Gender;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Player", propOrder = {
    "CURP",
    "NAME",
    "LAST_NAME",
    "SECOND_NAME",
    "BIRTHDAY",
    "POSITION",
    "DIRECTION",
    "GENDER",
    "PHONE",
    "EMAIL",
    "UPDATED_BY",
    "UPDATED_WHEN",
    "REGION"
})
@XmlRootElement(name="Player")
public class Player {

    @XmlElement(required = true)
    protected String curp;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String lastName;
    protected String secondName;
    
    @XmlElement(required = true)
    private String birthday;
    
    @XmlElement(required = true)
    protected String position;
    @XmlElement(required = true)
    protected String direction;
    @XmlElement(required = true)
    protected String gender;
    @XmlElement(required = true)
    protected String phone;
    @XmlElement(required = true)
    protected String email;
    @XmlElement(required = true)
    protected String upatedBy;
    
    @XmlElement(required = true)
    private String updatedWhen;
    
    @XmlElement(required = true)
    protected int region;
    
    
    
	public Player() {
		super();
	}
	public Player(String curp, String name, String lastName, String secondName,
			String birthday, String position, String direction, String gender,
			String phone, String email, String upatedBy, String updatedWhen,
			int region) {
		super();
		this.curp = curp;
		this.name = name;
		this.lastName = lastName;
		this.secondName = secondName;
		this.birthday = birthday;
		this.position = position;
		this.direction = direction;
		this.gender = gender;
		this.phone = phone;
		this.email = email;
		this.upatedBy = upatedBy;
		this.updatedWhen = updatedWhen;
		this.region = region;
	}
	public String getCurp() {
		return curp;
	}
	public void setCurp(String curp) {
		this.curp = curp;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getLastName() {
		return lastName;
	}
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	public String getSecondName() {
		return secondName;
	}
	public void setSecondName(String secondName) {
		this.secondName = secondName;
	}
	
	public String getPosition() {
		return position;
	}
	public void setPosition(String position) {
		this.position = position;
	}
	public String getDirection() {
		return direction;
	}
	public void setDirection(String direction) {
		this.direction = direction;
	}
	public String getGender() {
		return gender;
	}
	public void setGender(String gender) {
		this.gender = gender;
	}
	public String getPhone() {
		return phone;
	}
	public void setPhone(String phone) {
		this.phone = phone;
	}
	public String getUpatedBy() {
		return upatedBy;
	}
	public void setUpatedBy(String upatedBy) {
		this.upatedBy = upatedBy;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public int getRegion() {
		return region;
	}
	public void setRegion(int region) {
		this.region = region;
	}
	public String getBirthday() {
		return birthday;
	}
	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}
	public String getUpdatedWhen() {
		return updatedWhen;
	}
	public void setUpdatedWhen(String updatedWhen) {
		this.updatedWhen = updatedWhen;
	}
	
	public static toString ()
	{
		System.out.println ("juan ");
	}

  }
