//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vIBM 2.2.3-11/28/2011 06:21 AM(foreman)- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 09:14:11 AM GMT-06:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bharatthippireddy.com/Patient", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bharatthippireddy.patient;
